
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"/home/veras/Veras/Aplicações/APAM/build/assets/")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("859x468")
window.configure(bg = "#19AECF")


canvas = Canvas(
    window,
    bg = "#19AECF",
    height = 468,
    width = 859,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    12.0,
    12.0,
    28.666589736938477,
    24.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    67.0,
    50.0,
    244.0,
    69.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    644.0,
    50.0,
    821.0,
    69.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    335.0,
    50.0,
    512.0,
    69.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    67.0,
    111.0,
    244.0,
    130.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    641.0,
    111.0,
    818.0,
    130.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    335.0,
    111.0,
    512.0,
    130.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    335.0,
    172.0,
    512.0,
    191.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    67.0,
    233.0,
    244.0,
    252.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    641.0,
    233.0,
    818.0,
    252.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    335.0,
    233.0,
    512.0,
    252.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    67.0,
    28.0,
    anchor="nw",
    text="Data",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    335.0,
    28.0,
    anchor="nw",
    text="Endereço de e-mail",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    641.0,
    28.0,
    anchor="nw",
    text="Nome completo",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    67.0,
    88.0,
    anchor="nw",
    text="CPF",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    335.0,
    88.0,
    anchor="nw",
    text="RG",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    641.0,
    88.0,
    anchor="nw",
    text="Data de nascimento",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    67.0,
    149.0,
    anchor="nw",
    text="Gênero",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    335.0,
    149.0,
    anchor="nw",
    text="Naturalidade",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    641.0,
    149.0,
    anchor="nw",
    text="Estado Civil",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    67.0,
    213.0,
    anchor="nw",
    text="Endereço completo",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    335.0,
    213.0,
    anchor="nw",
    text="Telefone fixo (Opcional)",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    644.0,
    213.0,
    anchor="nw",
    text="Celular",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_rectangle(
    67.0,
    294.0,
    244.0,
    313.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    641.0,
    294.0,
    818.0,
    313.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    335.0,
    294.0,
    512.0,
    313.0,
    fill="#FFFFFF",
    outline="")

canvas.create_rectangle(
    67.0,
    355.0,
    244.0,
    374.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    67.0,
    274.0,
    anchor="nw",
    text="Nome da empresa de trabalho",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    335.0,
    274.0,
    anchor="nw",
    text="Endereço da empresa de trabalho",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    641.0,
    274.0,
    anchor="nw",
    text="Telefone da empresa de trabalho",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_text(
    67.0,
    334.0,
    anchor="nw",
    text="Profissão",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_rectangle(
    338.0,
    355.0,
    515.0,
    374.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    338.0,
    334.0,
    anchor="nw",
    text="Com qual valor mensal poderia colaborar?",
    fill="#FFFFFF",
    font=("Inter Bold", 12 * -1)
)

canvas.create_rectangle(
    718.0,
    414.0,
    834.0,
    446.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    67.0,
    172.0,
    244.0,
    191.0,
    fill="#000000",
    outline="")

canvas.create_text(
    350.0,
    178.0,
    anchor="nw",
    text="Placeholder",
    fill="#828282",
    font=("Inter", 10 * -1)
)

canvas.create_rectangle(
    213.0,
    170.0,
    234.0,
    191.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    485.0,
    170.0,
    506.0,
    191.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    644.0,
    172.0,
    821.0,
    191.0,
    fill="#FFFFFF",
    outline="")

canvas.create_text(
    658.0,
    178.0,
    anchor="nw",
    text="Placeholder",
    fill="#828282",
    font=("Inter", 10 * -1)
)

canvas.create_rectangle(
    791.0,
    170.0,
    812.0,
    191.0,
    fill="#000000",
    outline="")

canvas.create_rectangle(
    218.0,
    51.0,
    233.0,
    66.0,
    fill="#FFFFFF",
    outline="")
window.resizable(False, False)
window.mainloop()
